language: python
jobs:
  include:
  - os: linux
    dist: bionic
    python: 3.6
  - os: linux
    dist: bionic
    python: 3.7
  - os: linux
    dist: bionic
    python: 3.8
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.8
install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash -i install_macos.sh; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash -i install_linux.sh; fi
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- conda activate fish2eod
script:
- pytest
after_success:
- bash create_deploy.sh
env:
  global:
  - secure: bZq/GzrIOIq++g1c7suayhYK591+dIW9PNGZSDpT+Jkm/42yjVbjpziuUenDTu2xFW1avBMR0JSpVinfw9Phr2ePdjllHnKmJt6kv+PbZq5WhnvghlyZnqwXE9XpV7iNaSS0E2cp69tJx3z4bbDGRr5XzWnGOXF7MjV43l9YCvIWFNZyIBoJ0Oc00VJi8CFu+Aqj/AD30gRZiIr073HrvKcIXSJZOLOT9WUbvl8hUB9+/ZnJ/7CBJsrkEIh+A0i118Hrl8vlCnHEUsth8apHbW0xsXRPPbx7hvGlFR5pLFuyfGCa4/whRvhDY5Y2yhEcdXBnO7env4zSGqs7RkqpNXfOo9FNP9a/p9vYadWsJtXbp6kkdBkm1mttStORCJE5Uic5f4zNcZSTNOv93cHw49RXrWPwol7DKy+HapraiqiPQcDJSwddc96jTIgLE/OevL3lXQjtskNhjJWUsT7ztUZeX3yiWFfYgJ7gzQ0utUuVayS0GuDVHUCbmSclLBktKBJjWNwf4amRZTSjo1vRBsixkkXaQeh61qASqAi2Ypnop4k07wXiXCbqGQxgKt5tdO9rkUhLKFUJ7mmF75kb6e6ghAub7Qo2L2OIPQTDo4/IauJk17TthDS0bSACgcbt32S5aLo31E4BIIPcvzwR3upNEXqh9JH6vyvE4L3xuDo=
