# conda env create -f conda_environment.yml
# conda env update --file conda_environment.yml --name ENV_NAME

name: fish2eod
channels:
  - defaults
dependencies:
  - conda-forge::fenics-dolfin==2019.1.0
  - pytest
  - pytest-runner
  - pytest-cov
  - tqdm
  - PyYAML
