# conda env create -f conda_environment.yml
# conda env update --file conda_environment.yml --name ENV_NAME

name: fish2eod
channels:
  - defaults
  - conda-forge
dependencies:
  - fenics-dolfin==2019.1.0
  - superlu_dist==7.2.0
#  - gmsh
  - pytables
  - h5py
  - matplotlib
  - meshio<6
  - numpy
  - scipy
  - pandas
  - tqdm
  - PyYAML
  - Shapely
  - lxml
  - dataclasses
  - pip
  - pip:
    - Sphinx>=2.0
    - sphinx_rtd_theme
    - ipython
    - sphinx_autodoc_typehints

