# conda env create -f conda_environment.yml
# conda env update --file conda_environment.yml --name ENV_NAME

name: fish2eod
channels:
  - defaults
dependencies:
  - conda-forge::fenics-dolfin==2019.1.0
  - conda-forge::superlu_dist==7.2.0
  - pip
  - pip:
    - pygmsh==6.1.1 # pin to pre v7 TODO update to be compatible and update GMSH
    - tables
    - h5py --no-binary=h5py # conda or pip?
    - matplotlib>3.2 # bugfix for conda solving on py3.6
    - meshio
    - numpy
    - scipy
    - pandas
    - tqdm
    - PyYAML
    - Shapely
    - lxml
    - dataclasses
    - Sphinx>=2.0
    - sphinx_rtd_theme
    - ipython
    - sphinx_autodoc_typehints

