# conda env create -f conda_environment.yml
# conda env update --file conda_environment.yml --name ENV_NAME

name: fish2eod
channels:
  - defaults
  - conda-forge
dependencies:
  - fenics-dolfin==2019.1.0
  - superlu_dist==7.2.0
  - gmsh==3.0.6
  - pytables
  - h5py
  - matplotlib
  - meshio<5
  - numpy
  - scipy
  - pandas
  - tqdm
  - PyYAML
  - Shapely
  - lxml
  - dataclasses
  - pip
  - ipython
  - sphinx-autodoc-typehints
  - slepc==3.16.1
  - slepc4py==3.16.1
  - petsc==3.16.6
  - petsc4py==3.16.6

