name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with tmate debugging enabled
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 6'

jobs:
  pytest:
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Log Conda Environment
        run: |
          mamba info
          mamba list

      - name: Install Dependencies
        run: |
          mamba install pytest pytest-cov
          pip install pytest-forked

      - name: Install libglu1-mesa
        if: matrix.os == 'ubuntu-18.04'
        run: sudo apt-get install -y libglu1-mesa

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Run Tests
        # Fork the tests to manage memory between tests (PR #1)
        run: |
          pytest --cov=./ --cov-report=xml --forked

      - name: Store Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_report
          path: ./coverage.xml

  upload-to-codecov:
    needs: pytest
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true
          fail_ci_if_error: true